### ISSUE TITLE
Alphabetise wordsearch clues

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#21]
Alphabetise the words along the side of the grid so that it is more easy to read and find the word you are looking at.  (Or order them in some other way.)

**Comment by AndrewRigg** [comment]
Removed this comment to a new issue.

**Comment by Golpette** [comment]
Heya. Why would alphabetising the words make anything easier? It would be easy to do but I think it'd look a little weird... in normal sized wordsearches we'll never have more than ~20 anyway.

Actually, we could specify a maximum number of words per game rather than just randomly fitting as many as possible (maybe dependent on grid size?).

I like the idea of scoring out correctly found words. Maybe best to delete this issue and make one specifically for that? We won't be able to do this though, until we have a method of selecting words but once we do, adding a black line along the coords of the word wouldn't be tricky.

**Comment by AndrewRigg** [comment]
Looking at google images, it seems to be about half and half, whether word searches have alphabetised words.  I think it comes down to preference.  Do you not think that being able to find the word easily would be handy for users?

**Comment by AndrewRigg** [comment]
Rather than automatically alphabetising, we could allow the user to choose how to order them.  Options could be alphabetically, size of word, directions, complete/incomplete.  These could also be used in combination ie, order by completed words and in alphabetical order in each list.

**Comment by AndrewRigg** [comment]
OK, I have completed this and given the user the option of choosing between ordering largest to smallest (alphabetical), smallest to largest (alphabetical), alphabetical and randomly.  The user hovers the mouse over the area with the word list and then an option menu pops up which allows them to select the ordering.  The pop up then disappears but can be reactivated by hovering over the grid area.
