### ISSUE TITLE
Sort the fill in method to have a weighted but appropriate method to add in larger words first

### ISSUE THREAD

**Issue by AndrewRigg** [AndrewRigg/Crossword#7]

**Comment by Golpette** [comment]
The branch fittingProc contains updated fitting procedure.

(1) Fixed error introduced when adding "across" boolean field. Crosswords are generated much quicker now.

(2) We now force the top left, top right and bottom left sites to be occupied (there was a weird bug when doing bottom right too which I didn't figure out yet) which make the crossword look more prettier than befory. The biggestFirst boolean variable determines whether we fit the largest possible word, or randomly sized words, and you can set by hand how many randomly sized words are entered before we always force the largest fit - doing this makes the crosswords prettier and makes them more likely to be connected

(3) There is also a new class fitWord_forceConnection which was a test of a different procedure: instead of randomly trying to throw down words and then using Hoshen-Kopelman to check if grid is connected, using this procedure forces every new word added to be connected to at least one of the existing words, hence we lways succeed first time. Crosswords do not look as nice with this procedure, though it may be necessary when using smaller word lists such as Spanish animals etc.
